from fastapi import APIRouter

from app.api.v1 import auth, users, organizations, projects, documents, websites, bots, chat, code, api_keys, credits, notifications, admin, agents, billing, marketplace, marketplace_extended, analytics, integrations, voice, vision, video, business, agent_network, code_studio, industry_solutions, global_infrastructure, v3_personal, v3_organization, v3_creation, v3_collaboration, v4_cloud, v4_enterprise, v4_ecosystem, v5_knowledge, v5_copilot, v5_simulation, v5_compliance, v5_connector, v5_collaboration, v6_governance

api_v1_router = APIRouter()

api_v1_router.include_router(auth.router, prefix="/auth", tags=["Authentication"])
api_v1_router.include_router(users.router, prefix="/users", tags=["Users"])
api_v1_router.include_router(organizations.router, prefix="/organizations", tags=["Organizations"])
api_v1_router.include_router(projects.router, prefix="/projects", tags=["Projects"])
api_v1_router.include_router(documents.router, prefix="/documents", tags=["Documents"])
api_v1_router.include_router(websites.router, prefix="/websites", tags=["Websites"])
api_v1_router.include_router(bots.router, prefix="/bots", tags=["Bots"])
api_v1_router.include_router(chat.router, prefix="/chat", tags=["Chat"])
api_v1_router.include_router(code.router, prefix="/code", tags=["Code"])
api_v1_router.include_router(api_keys.router, prefix="/api-keys", tags=["API Keys"])
api_v1_router.include_router(credits.router, prefix="/credits", tags=["Credits"])
api_v1_router.include_router(notifications.router, prefix="/notifications", tags=["Notifications"])
api_v1_router.include_router(admin.router, prefix="/admin", tags=["Admin"])
api_v1_router.include_router(agents.router, prefix="/agents", tags=["AI Agents"])
api_v1_router.include_router(billing.router, prefix="/billing", tags=["Billing & Subscriptions"])
api_v1_router.include_router(marketplace.router, prefix="/marketplace", tags=["Marketplace"])
api_v1_router.include_router(analytics.router, prefix="/analytics", tags=["Analytics"])
api_v1_router.include_router(integrations.router, prefix="/integrations", tags=["Integrations"])
api_v1_router.include_router(voice.router, prefix="/voice", tags=["Voice AI"])
api_v1_router.include_router(vision.router, prefix="/vision", tags=["Vision AI"])
api_v1_router.include_router(video.router, prefix="/video", tags=["Video AI"])
api_v1_router.include_router(business.router, prefix="/business", tags=["Business AI"])
api_v1_router.include_router(agent_network.router, prefix="/agent-network", tags=["Agent Network"])
api_v1_router.include_router(code_studio.router, prefix="/code-studio", tags=["Code Studio"])
api_v1_router.include_router(marketplace_extended.router, prefix="/marketplace-extended", tags=["Marketplace Ecosystem"])
api_v1_router.include_router(industry_solutions.router, prefix="/industry", tags=["Industry Solutions"])
api_v1_router.include_router(global_infrastructure.router, prefix="/infrastructure", tags=["Global Infrastructure"])
api_v1_router.include_router(v3_personal.router, prefix="/v3/personal", tags=["V3 Personal AI"])
api_v1_router.include_router(v3_organization.router, prefix="/v3/organization", tags=["V3 Autonomous Organization"])
api_v1_router.include_router(v3_creation.router, prefix="/v3/creation", tags=["V3 Creation Engine"])
api_v1_router.include_router(v3_collaboration.router, prefix="/v3/collaboration", tags=["V3 Collaboration"])
api_v1_router.include_router(v4_cloud.router, prefix="/v4/cloud", tags=["V4 Cloud Platform"])
api_v1_router.include_router(v4_enterprise.router, prefix="/v4/enterprise", tags=["V4 Enterprise"])
api_v1_router.include_router(v4_ecosystem.router, prefix="/v4/ecosystem", tags=["V4 Ecosystem"])
api_v1_router.include_router(v5_knowledge.router, prefix="/v5/knowledge", tags=["V5 Knowledge Intelligence"])
api_v1_router.include_router(v5_copilot.router, prefix="/v5/copilot", tags=["V5 Industry Copilots"])
api_v1_router.include_router(v5_simulation.router, prefix="/v5/simulation", tags=["V5 Simulation Intelligence"])
api_v1_router.include_router(v5_compliance.router, prefix="/v5/compliance", tags=["V5 Compliance Intelligence"])
api_v1_router.include_router(v5_connector.router, prefix="/v5/connector", tags=["V5 Connector Platform"])
api_v1_router.include_router(v5_collaboration.router, prefix="/v5/collaboration", tags=["V5 Multimodal Collaboration"])
api_v1_router.include_router(v6_governance.router, tags=["V6 AI Governance"])
