version: "3.9"

services:
  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../../backend:/app

  frontend:
    command: npm run dev
    volumes:
      - ../../frontend:/app
      - /app/node_modules
